src/objects/Business_Plan__c.object
<CustomObject>
    <fields>
        <fullName>PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan For</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>contains</operation>
                <value>Channel Partner / Reseller, Installation Partner, Technology Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>Business_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <displayFormat>PLAN-{0000}</displayFormat>
        <label>Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Goals__c.object
<CustomObject>
    <fields>
        <fullName>BusinessPlan__c</fullName>
        <label>Business Plan</label>
        <referenceTo>Business_Plan__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL-{0000}</displayFormat>
        <label>Goal #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestbusinessPlanTrigger.cls
@isTest
public class TestbusinessPlanTrigger {
    
     public static User createPartnerUser() {
        
        Account a = new Account(name = 'Partner Account', Type = 'Technology Partner');
        insert a;
        
        Contact c = new Contact(LastName = 'PartnerTest', AccountId = a.Id);
        insert c;
        
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'Custom Partner Community Login User'].Id,
            LastName = 'Test',
            Email = 'test@partneraccount.com',
            Username = 'test@partneraccount.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'Plan Mgr',
            Alias = 'Planmgr',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ContactId = c.Id
            
        );
        
        insert u;
        
        return [SELECT ID, CONTACTID, ACCOUNTID FROM USER WHERE ID = :U.Id LIMIT 1];
    }
    
    
   
    public static testmethod void updateGoalsRecordType_forPublishedPlans() {
        User partnerUser = createPartnerUser();
        
        //Test setup
        
        Business_Plan__c samplePlan = new Business_Plan__c(PartnerAccount__c = partnerUser.AccountId, Status__c = 'Draft', ownerid = partnerUser.Id);
        insert samplePlan;
        
        
        Schema.DescribeSObjectResult R = Goals__c.SObjectType.getDescribe();
        Map<String,Schema.RecordTypeInfo> goalRecordTypeInfo = R.getRecordTypeInfosByName();
        
        Id unpublishedplan_rt = goalRecordTypeInfo.get('Unpublished Plan').getRecordTypeId();
        Id publishedplan_rt = goalRecordTypeInfo.get('Published Plan').getRecordTypeId();
 
        Goals__c newGoal = new Goals__c(BusinessPlan__c = samplePlan.Id, Priority__c = '1', recordtypeid = unpublishedplan_rt);
        insert newGoal;
        
        Test.startTest();

          samplePlan.cplan__Status__c = 'Published';
          update samplePlan;

        
        Test.stopTest();
        
        //Assertion
  
        List<Goals__c> allGoals = [SELECT ID, RECORDTYPEID FROM GOALS__C WHERE BusinessPlan__c = :samplePlan.Id ];
        System.assertEquals(publishedplan_rt, allGoals[0].recordtypeid);
        
    }
}